# -*- coding: utf-8 -*-
"""
Created on Mon Nov 13 15:10:53 2017

@author: Joe McCauley (joe.mccauley@tcd.ie)
Updates:
24/09/2026 by Ciara Deasy-Millar (deasymic@tcd.ie) to read images in xst files which contain multiple images
Originally written for Python 2.7
Upgraded for Python 3.8 April 2021
Based on a translated matlab script originally from ASTRON for processing
•xst data from an international LOFAR station.

This incarnation:
Can take into account the rotation of the station wrt the core station.
(Default rotation is 11.9 degrees for IE613)
Processes X polarisation, Y polarisation or both X & Y.
The data source should be the first command argument & must be a valid
filename or folder. If the data source is a folder, then all xst files
in that folder will be processed.
The code relies on the target XST data file name being like '20181003_153426_sb281_xst.dat'

Output is fed to the script PlotAllSky.py which plots the data on an
ortho projected polar grid and saves as an image with main sky source
positions plotted.
PlotAllSky.py should be in the same folder as this script.
PlotAllSky.py plots the data generated by this file on an ortho polar grid
along with markers for CasA, CygA and the Sun for the time & data of the
observation.
PlotAllSky.py uses matplotlib v2.0.2 or 2.1.1 (NOT 2.1.0) Also needed is
Astropy.

Antenna positions, HBA deltas and calibration files are specified in an
external file called SkyMultimap_vars.py. That file should be in the same
folder as this script.

As an aid in locating the physical position of RFI in a subband, you can
click a suspect 'hotspot' on an interactive plot generated by PlotAllSky.py
and a popup annotation will give a bearing & elevation to the source. This only works when
processing a single file.

Sometimes sources don't line up nicely, particularly at low elevations, this may
possibly be attributed to ionospheric refraction at low elevations
(Derek McKay, Dublin data school 2018).

Requires an internet connection to get source positions for the observation(s)
Tested on Windows 7/10x64 & Ubuntu 16.04

"""
import pandas as pd
import numpy as np
from subprocess import Popen, PIPE
import re
from scipy import ndimage
import glob
import sys
from pathlib import Path
import PlotAllSky
import SkyMultiMap_vars as ext_vars
from filesplit.split import Split 
import os

# splits an xst file that contains more than one image up into a directory containing the individual image files for processing 
def split_file(datasource):

    #output_dir = datasource.split('/')
    #output_dir = f'{output_dir[0]}/{output_dir[1]}/{output_dir[2]}/{output_dir[3]}/{output_dir[-1]}/splitdata/' # need to fix this to make it more accessible rather than something that works on just my mac
    #output_dir = f'splitdata/{datasource}'
    output_dir = os.path.join(os.path.dirname(datasource), 'splitdata') + '/'

    if not os.path.exists(output_dir): 
       os.makedirs(output_dir) # make the directory if it doesnt exits 

    split = Split(inputfile= datasource, outputdir= output_dir) # splits the file up by size seems to work well siince size is consistent 
    split.bysize(size=589824)

    datasource = output_dir # now the datasource is the new directory of split files so the format holds from og code

    return datasource

def process_path(datasource)  : #converts '\' to '/' in paths pasted in from windows PCs

    # checks size of file
    file_size = os.path.getsize(datasource)
    print(file_size)

    # if its bigger than this then it containes more than one image so we need to split it up
    if file_size > 589824:
       print(f'datasource is one xst file with multiple images, size {file_size} bytes')
       datasource = split_file(datasource)
       print(datasource)
    else:
       datasource = datasource 


    if Path(datasource).is_dir() or Path(datasource).is_file():
      datasource=re.sub(r"\ddd", "/ddd", datasource) # just in case you have a '/nnn' in the string which might be interpeted as an escape sequence
      #datafile=re.sub(r"\\", "/", datafile)
      #datafile=os.path.normpath(datafile)
      return datasource
    else:
      print ('You must specify a valid data folder or data file.\nExiting...')
      sys.exit()

def process_files(datasource):
    #filenames=glob.glob(datasource + '*xst.dat')
    #filenames = glob.glob(datasource + '*xst_*.dat')
    filenames = glob.glob(datasource + '*xst[_.]*dat') # now this works for both types of directories (those from an actual directory and those from directories made from splitting an xst file)
    #print(filenames)
    filenames.sort()
    print (str(len(filenames)) + ' xst data files to be processed....')
    return filenames

def save2csv( filename, array):
    df=pd.DataFrame(array)
    df.to_csv(filename)

#Run a given process on the local machine and return either the program output or just the error code
#Usage Popen('remote/folder/remote command, True) will run the rempte command and only return the remote command exit code
def RunSubProcess(Process, ReturnCodeOnly = False):
    print (Process)
    p = Popen(Process, shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE)
    output, err = p.communicate(b"input data that is passed to subprocess' stdin")
    if ReturnCodeOnly is True:
        return p.returncode
    else:
        return output#,err

def CalcFreq(rcumode, subband):
    if rcumode == 5:
        freqoff = 100e6;
        basefreq = 200.0;
    elif rcumode == 6:
        freqoff = 160e6;
        basefreq = 160.0;
    elif rcumode == 7:
        freqoff = 200e6;
        basefreq = 200.0;
    else:
        freqoff = 0;
        basefreq = 200.0;
    frequency = ((basefreq / 1024 ) * subband + (freqoff/1e6))
    return frequency, freqoff

def readCalTable(calfile):

  # [calx, caly, header] = readCalTable(calfile)
  #
  # Read calibration table from a properly formatted calibration table file.
  #
  # Argument
  # calfile : file name of calibration table file
  #
  # Return values
  # calx   : Nelem x Nsb (48 x 512 for Dutch stations, 96 x 512 for European
  #          stations) matrix containing a complex valued correction factor
  #          for each element and each subband for the array of x-elements.
  # caly   : corresponding result for the array of y-elements.
  # header : header of calibration table
  #
  # SJW, 18 October 2011
  # modified by SJW on 3 February 2012 (header in calibration tables)
  # modified by ME on 27 February 2012 (according to latest header
  # definitions.
  # N.B. this version is able to read CalTables with or with no headers.

  # get file descriptor
  fid = open(calfile, 'rb')
  # distinguish between CalTable files with or without headers; newer
  # CalTable files should contain headers
  header = bytearray()

  newline = fid.readline()

  if b'HeaderStart' in newline:
      position_indicator=fid.tell()
      newline = fid.readline()
      fid.seek(position_indicator)
      while b'HeaderStop' not in newline:
           curchar = fid.read(1)
           print( str(curchar))
           header.extend(curchar)#+=curchar
           if curchar == b'\n' or curchar == b'\r':
               position_indicator=fid.tell()
               newline = fid.readline()
               fid.seek(position_indicator)
      newline = fid.readline()                    # dummy value
  else:
      fid.seek(0)                          # set position descriptor to beginning of file
  # read CalTable
  position_indicator=fid.tell()
  fid.seek(position_indicator)
  data = np.fromfile(fid, dtype=np.float64)
  fid.close()
  Nrcu = len(data) / (2 * 512)
  comp=data[0::2] + 1j * data[1::2]
  cal = np.reshape(comp, (int(Nrcu), 512), order='F') 
  caly = cal[1::2]
  return calx, caly, header

def parseiHBAField(afilename, ifilename, selection, rcumode, EU):

    # [posxpol, posypol, lon, lat, refpos, rotmat] =
    #     parseiHBAField(filename, ifilename, selection, rcumode, EU)
    #
    # Parser for AntennaFields.conf and iHBADeltas.conf files.
    #
    # arguments
    # filename : filename (including path if necessary) of the AntennaFields.conf
    #            file
    # ifilename: filename (including path if necessary) of the iHBADeltas.conf
    #            file
    # selection: element number per tile [0..15]
    # rcumode  : RCU mode number (determines array configuration)
    # EU       : true for European stations
    #
    # return values
    # posxpol : Nelem x 3 matrix with (x, y, z)-positions of x-dipoles (in m)
    #           w.r.t. the reference position in ITRF coordinates
    # posypol : Nelem x 3 matrix with (x, y, z)-positions of y-dipoles (in m)
    #           w.r.t. the reference position in ITRF coordinates
    # lon     : geographic longitude of the station (in degrees)
    # lat     : geographic latitude of the station (in degrees)
    # refpos  : Nelem x 3 vector with (x, y, z)-coordinate of ITRF reference
    #           position of the specified antenna array (in m)
    # rotmat  : 3 x 3 rotation matrix to convert ITRF to local coordinates
    #
    # SJW, January 2011
    # modified by SJW, January 2012
    # including iHBADeltas.conf by MJN, November 2015
    # update new format Antenna Field size by MJN, June 2017

    # read in delta positions HBA elements
    arrayname = 'HBADeltas'
    fid = open(ifilename, 'r')
    # skip the first 4 comment lines
    for k in range (5):
        fid.readline() # ead 4 lines & discard
    # looking for token arrayname
    token = fid.readline()
    if arrayname in token:
        print ('delta positions found, parsing...')
        arraysize = fid.readline()[0:6]
        Nant = int(arraysize[len(arraysize)-3:len(arraysize)-1])+1

        refpos = 0
        # obtain element offset positions
        posxelem = []
        posyelem = []
        for idx in range( 0,Nant):
          token = fid.readline()
          posxelem.extend(float (i) for i in re.findall(r"[-+]?\d*\.\d+|\d+", token))
        posxelem = np.reshape(posxelem, (Nant, 3))
        posyelem = posxelem
    else:
        print ('delta positions not found')
        posxelem = []
        posyelem = []
        return
    fid.close()

    # parse for antenna locations
    if rcumode in [1, 2, 3, 4]:
        arrayname = 'LBA'
    else:
        arrayname = 'HBA'

    fid = open(afilename, 'r')
    token = fid.readline()
    while arrayname not in token or 'NORMAL_VECTOR' in token or 'ROTATION_MATRIX' in token or len(token) == 1:
        token = fid.readline()
    if arrayname in token:
        refpos=[]
        print ('configuration found, parsing...')
        token = fid.readline()[8:]
        refpos.extend(float (i) for i in re.findall(r"[-+]?\d*\.\d+|\d+", token))
        # obtain antenna locations
        arraysize = fid.readline()[0:6]
        if (EU == 0) and (arrayname == 'LBA'):
            Nelem = int(arraysize[len(arraysize)-3:len(arraysize)-1])
            Nelem=Nelem+1
            Nelem=Nelem/2
        else:
            Nelem = int(arraysize[len(arraysize)-3:len(arraysize)-1])+1
        posxpol = np.zeros((Nelem, 3),dtype=float)
        posypol = np.zeros((Nelem, 3),dtype=float)
        for idx in range( 0,Nelem):
            line=[]
            token = fid.readline()
            line.extend(float (i) for i in re.findall(r"[-+]?\d*\.\d+|\d+", token))
            posxpol[idx,:]=line[0:3]
            posxpol[idx,:] = posxpol[idx,:] + posxelem[selection[idx],:]
            posypol[idx,:]=line[3:]
            posypol[idx,:] = posypol[idx,:] + posyelem[selection[idx],:]
    else:
        print ('configuration not found')
        posxpol = []
        posypol = []
        lon = []
        lat = []
        return
    fid.close()

    # select the right set of antennas
    if EU == 1:
        sel = range(0,96)
    else:
        if rcumode in [1, 2]:
            sel = range(Nelem/2,Nelem) #sel=25:48
        elif rcumode in [3, 4]:
            sel = range(0,Nelem/2)         #sel=1:24
        else:
            sel = range(0,Nelem)
    posxpol = posxpol[sel, :]
    posypol = posypol[sel, :]

#    # obtain rotation matrix
    fid = open(afilename, 'r')
    token = fid.readline()
    while arrayname not in token[len(token)-5:len(token)-1] or 'ROTATION_MATRIX' not in token or len(token) == 1:
        token = fid.readline()
    token = fid.readline()
    rotmat = np.zeros((3, 3),dtype=float)
    for idx in range( 3 ):
        line=[]
        token = fid.readline()
        line.extend(float (i) for i in re.findall(r"[-+]?\d*\.\d+|\d+", token))
        rotmat[idx,:]=line[0:3]
    rotmat=rotmat.T #has to be transposed to get into correct format for further operations below
    token = fid.readline() # 3 line reads needed for compatibility with the next block
    token = fid.readline()
    token = fid.readline()
    fid.close();
    # convert antenna positions to local horizon coordinate system
    fid = open(afilename, 'r')
    if 'HBA0' in token:
        print ('')
####Matlab code. Needs porting for completeness
#        while ~((strcmp(token, 'HBA1') && strcmp(prevtoken, 'ROTATION_MATRIX')) || isempty(token))
#            prevtoken = token;
#            token = fscanf(fid, '#s', 1);
#        end
#        fscanf(fid, '#s', 4);
#        rotmat2 = zeros(3, 3);
#        rotmat2(:) = fscanf(fid, '#f', 9);
#        posxpol(1:Nelem/2, :) = posxpol(1:Nelem/2, :) / rotmat;
#        posxpol(Nelem/2+1:Nelem, :) = posxpol(Nelem/2+1:Nelem, :) / rotmat2;
#        posypol(1:Nelem/2, :) = posypol(1:Nelem/2, :) / rotmat;
#        posypol(Nelem/2+1:Nelem, :) = posypol(Nelem/2+1:Nelem, :) / rotmat2;
####Matlab code end
    else:
        posxpol = np.matrix(posxpol)
        rotmat = np.matrix(rotmat)
        posxpol = posxpol*np.linalg.pinv( rotmat ) #right matrix division
        posypol = posypol*np.linalg.pinv( rotmat )
    fid.close();

    # obtain longitude and latitude of the station
    wgs84_f = 1 / 298.257223563
    wgs84_a = 6378137
    wgs84_e2 = wgs84_f * (2 - wgs84_f)
    lon = np.arctan2(refpos[1], refpos[0])
    lon=lon* 180 / np.pi
    r = np.sqrt(refpos[0]**2 + refpos[1]**2)
    prev_lat = 100000
    lat = np.arctan2(refpos[2], r)
    while (abs(lat - prev_lat) >= 1e-12):
        prev_lat = lat
        normalized_earth_radius = 1 / np.sqrt((1-wgs84_f)**2 * np.sin(lat)**2 + np.cos(lat)**2)
        lat = np.arctan2(wgs84_e2 * wgs84_a * normalized_earth_radius * np.sin(lat) + refpos[2], r)
    lat = lat * 180 /np.pi
    return posxpol, posypol, lon, lat, refpos, rotmat

def acm2skyimage(acm, xpos, ypos, freq, lo, m):
#
# conversion of ACM to sky image
#
# arguments
# acm    : nelem x nelem x nchannel array correlation matrix
# xpos   : x-position of antennas (vector of length nelem)
# ypos   : y-position of antennas (vector of length nelem)
# freq   : frequencies in Hz (vector of length nchannel)
# l, m   : l and m points to which to direct the array (vectors)
#
# return value
# skymap : length(l) x length(m) x nchannel matrix containing the
#          resulting sky maps
#
# SJW, 2004
#
# modified April 19, 2005 by SJW: correct coordinate conventions
# modified July 20, 2006 by SJW: optimization for release in LOFAR package

  [nelem, dummy] = np.shape(acm)
  nchannel = 1 #(its always one)
  c  = 2.9979245e8

  skymap = np.zeros((len(l), len(m)))#, nchannel)

  for nch in range (0, nchannel):
    print ('acm2skyimage: working on channel ' + str(nch+1) + ' of ' + str(nchannel))
    wavelength = c / freq #(nch)
    k = (2 * np.pi) / wavelength
    wx = np.exp(-1j * k * xpos[:] * lo)#.')
    wy = np.exp(-1j * k * ypos[:] * m)#.')
    #wz = exp(-i * k * zpos(:) * (sqrt (1 - l(:).^2 - m(:).^2)).')
    for lidx in range ( 0, len(l)):
      for midx in range ( 0, len(m)):
        weight = np.multiply(wx[:, lidx], wy[:, midx]) # .* wz(:,midx);
        skymap[lidx,midx] = np.real(np.real(np.matrix(weight).H * np.matrix(acm[:, :]) * np.matrix(weight) ))[0,0]
  return skymap

def CreateAllSky( datafile, mulitple_files, rcumode, calx, caly, xpos, ypos, freq, l, m, process_x, process_y, ol_col, grid_thick, save_image, back_color, fore_color, int_time ):
    print (datafile)
    subband=int(datafile[datafile.find('_sb')+3:datafile.find('_',datafile.find('_sb')+3)]) #get the subband from the filename
    fid = open(datafile, 'r') # probably need to add the split just before this can define datafile to be for imagefile in datafile do the rest 
    # maybe need an if statement to say if datafile is greater than the standard 589,824 bytes then call the split function and then run the code for each spliut image
    data=np.fromfile(fid, dtype=np.float64)
    fid.close()
    comp=data[0::2] + 1j * data[1::2] # reconstructed data as complex numbers since alternating real and im
    acc = np.reshape(comp, (192, 192),order='F') # reshaping into 192x192 complex matrix.  
    frequency, freqoff = CalcFreq(int(rcumode), int(subband))

    #create a mask for the all sky image
    mask = np.ones((len(l),len(m)))
    dist = np.sqrt(np.square(np.meshgrid(l)) + np.square(np.matrix(np.meshgrid(m)).H))
    mask[dist >= 1] = np.nan

    if process_x == True:
      acccal = np.conj(np.outer(np.matrix(calx[:,subband]), np.matrix(calx[:,subband]).H )) * acc[::2, ::2]
      skymap = acm2skyimage(acccal, xpos, ypos, freq[subband-1] + freqoff, l, m)
      skymap=np.rot90(skymap,3)
      skymap=np.flipud(skymap)
      skymap=ndimage.rotate(skymap, station_rotation, mode='constant',cval=100, reshape=False)*mask
      polarity = 'X'
      PlotAllSky.main(datafile, skymap, rcumode, polarity, logplot, pixels, ol_col, grid_thick, back_color, fore_color, save_image, multiple_files, radial_label_angle, color_bar,  'IE613 (Birr)', int_time)
    if process_y == True:
      acccal = np.conj(np.outer(np.matrix(caly[:,subband]), np.matrix(caly[:,subband]).H ))* acc[1::2, 1::2]
      skymap = acm2skyimage(acccal, xpos, ypos, freq[subband-1] + freqoff, l, m)
      skymap=np.rot90(skymap,3)
      skymap=np.flipud(skymap)
      skymap=ndimage.rotate(skymap, station_rotation, mode='constant',cval=100, reshape=False)*mask
      polarity = 'Y'
      PlotAllSky.main(datafile, skymap, rcumode, polarity, logplot, pixels, ol_col, grid_thick, back_color, fore_color, save_image, multiple_files, radial_label_angle, color_bar, 'IE613 (Birr)', int_time)

###################################################################################################################
#End of function defines
###################################################################################################################

if __name__ == '__main__':
    from optparse import OptionParser
    o = OptionParser()
    o.set_usage('%prog datafile [options]')
    o.set_description(__doc__)
    o.add_option('-s', '--site', dest='site', default='Birr',
        help = 'The observing site name.')
    o.add_option('-m', '--rcumode', dest='rcumode', default=3,
        help = 'The RCU mode for the input data file.')
    o.add_option('-p', '--pixels', default=200, dest='pixels',
        help = 'option -p sets the # of pixels in the output data.')
    o.add_option('-g', '--grid_thick', default=0.5, dest='grid_thick',
        help = 'option -g sets the thickness of the overlay grid in the plot. Valid values are 0.1 to 1.')
    o.add_option('-o', '--overlay_col', default='black', dest='ol_col',
        help = 'option -o sets the color of the overlay in the plot.')
    o.add_option('-b', '--back_color', default='black', dest='back_color',
        help = 'option -b sets the color of the figure background.')
    o.add_option('-f', '--fore_color', default='white', dest='fore_color',
        help = 'option -f sets the color of the title, legend & colorbar ticks in the plot.')
    o.add_option('-i', '--save_image', action='store_true', default=False, dest='save_image',
        help = 'option -i saves a png file in the data folder.')
    o.add_option('-t', '--radial_label_angle', default=0, dest='radial_label_angle',
        help = 'option -t sets the angle for radial tick labels, 0 means no tick labels.')
    o.add_option('-r', '--rotation', default=-11.9, dest='station_rotation',
        help = 'option -r gives a station rotation (eg. IE613 is rotated by 11.9 degrees relative to CS002).')
    o.add_option('-x', '--process_x', action='store_true', default=False, dest='process_x',
        help = 'option -x processes data from X antennas, default is True.')
    o.add_option('-y', '--process_y', action='store_true', default=False, dest='process_y',
        help = 'option -y processes data from Y antennas.')
    o.add_option('-c', '--calibration', action='store_true', default=False, dest='calibration',
        help = 'option -c if true, uses calibration data from the specified calibration file for a given rcu mode, default is False.')
    o.add_option('-l', '--logplot', action='store_true', default=False, dest='logplot',
        help = 'option -l produces a log plot of the lofar xst data.')
    o.add_option('-e', '--int_time', default=False, dest='int_time', help='option -e gives the exposure/integration time (needed for xst files with multiple observations embedded)')
    opts, args = o.parse_args()#sys.argv[0:])

if args:
  datasource=process_path(args[0]) # verify that we have a valid datasource
else:
  print ('You must at least specify a valid datasource.\nExiting...')
  sys.exit()
station_rotation = float( opts.station_rotation )
rcumode = int(opts.rcumode) # you must specify the rcu mode
logplot = opts.logplot
save_image = opts.save_image #if true, then save an image with the same file root as the original filename
radial_label_angle = float( opts.radial_label_angle ) #the angle for radial ticks on the resultant plot
int_time = float(opts.int_time) if opts.int_time else 0
color_bar = True
ol_col = opts.ol_col
back_color = opts.back_color
fore_color = opts.fore_color
grid_thick = float(opts.grid_thick)
if grid_thick < 0.1:
    grid_thick = 0.1
    print ('Minimum grid thickness is 0.1')
elif grid_thick > 1:
    grid_thick = 1
    print ('Maxmum grid thickness is 1')
process_x = opts.process_x
process_y = opts.process_y
if process_x == False and process_y == False:
  #lets assume you wanted to process_x
  print ('No polarity specified, assuming X')
  process_x = True
calibration = opts.calibration # station cal status
stationtype=1
if not Path(ext_vars.antennafile).is_file():
  print ('The antennafile is not specified in the SkyMultiMap_vars.py file or is invalid.\nExiting...')
  sys.exit()
if not Path(ext_vars.ihbadeltafile).is_file():
  print ('The ihbadeltafile is not specified in the SkyMultiMap_vars.py file or is invalid.\nExiting...')
  sys.exit()
Generic_Int_201512 = [0,5,3,1,8,3,12,15,10,13,11,5,12,12,5,2,10,8,0,3,5,1,4,0,11,6,2,4,9,14,15,3,7,5,13,15,5,6,5,12,15,7,1,1,14,9,4,9,3,9,3,13,7,14,7,14,2,8,8,0,1,4,2,2,12,15,5,7,6,10,12,3,3,12,7,4,6,0,5,9,1,10,10,11,5,11,7,9,7,6,4,4,15,4,1,15]
posxpol, posypol, lon, lat, refpos, rotmat = parseiHBAField(ext_vars.antennafile , ext_vars.ihbadeltafile, Generic_Int_201512, rcumode, stationtype)

xpos = posxpol[:, 0]
ypos = posypol[:, 1]
pixels=float(opts.pixels) # need to keep pixels as a float for calculating image sizes
if pixels < 50.0:
    print ('Minimum image size is 50x50 pixels')
    pixels = 50.0

l = np.arange(  -1.0, 1.0 + ( 2/pixels ), 2/pixels )
m = l #its a 'square' image
freq=np.arange(0.0,100000000.0-0.001,100000000.0/512.0)
nelem = len(xpos)

if calibration == True:
  calstatus = 'Calibrated'
  # read calibration table
  if rcumode == 3:
    if not Path(ext_vars.mode3caldata).is_file():
      print ('The mode3 cal data file is not specified in the SkyMultiMap_vars.py file or is invalid.\nYou can run without the -c switch to plot data uncalibrated.\nExiting...')
      sys.exit()
    calx, caly, header = readCalTable( ext_vars.mode3caldata )
  if rcumode == 5:
    if not Path(ext_vars.mode5caldata).is_file():
      print ('The mode5 cal data file is not specified in the SkyMultiMap_vars.py file or is invalid.\nYou can run without the -c switch to plot data uncalibrated.\nExiting...')
      sys.exit()
    calx, caly, header = readCalTable( ext_vars.mode5caldata )
  if rcumode == 7:
    if not Path(ext_vars.mode7caldata).is_file():
      print ('The mode7 cal data file is not specified in the SkyMultiMap_vars.py file or is invalid.\nYou can run without the -c switch to plot data uncalibrated.\nExiting...')
      sys.exit()
    calx, caly, header = readCalTable( ext_vars.mode7caldata )
else:
   # uncalibrated data
   calstatus = 'Uncalibrated'
   nelem = 96
   calx = np.ones((nelem, 512), dtype = float)
   caly = np.ones((nelem, 512), dtype = float)

if Path(datasource).is_dir():
    filenames = process_files(datasource)
    multiple_files = True #process all files in the folder
    for datafile in filenames:
        CreateAllSky( datafile, multiple_files, rcumode, calx, caly, xpos, ypos, freq, l, m, process_x, process_y, ol_col, grid_thick, save_image, back_color, fore_color, int_time )
else:
    multiple_files = False  #process only the file given
    CreateAllSky( datasource, multiple_files, rcumode, calx, caly, xpos, ypos, freq, l, m, process_x, process_y, ol_col, grid_thick, save_image, back_color, fore_color, int_time )
